local popper = require("popper")

describe("popper.setup()", function()
  it("returns a table with start() and stop() methods", function()
    local result = popper.setup()
    assert.is_not_nil(result)
    assert.is_table(result)
    assert.is_function(result.start)
    assert.is_function(result.stop)
  end)

  it("is idempotent when called multiple times", function()
    local ok, err = pcall(function()
      popper.setup()
      popper.setup()
      popper.setup({ auto_start = true })
    end)

    assert.is_true(ok, tostring(err))
  end)
end)
